### ISSUE TITLE
Add Gradle wrapper

### ISSUE THREAD

**Issue by jglick** [jelmerk/maven-settings-decoder#5]
Since users of this project are, by definition, Maven developers, and since if you are like me you would not want to run a tool like this on a precompiled binary, it would be polite to include a `gradlew` file in the repository to make it as foolproof as possible to build—along with instructions on how to use the build product: I had to find from trial and error that `build/scripts/maven-settings-decoder` does not work and you actually need to unpack `build/distributions/maven-settings-decoder.zip`.

**Comment by jelmerk** [comment]
Added and updated documentation
