### ISSUE TITLE
Specify Java target level

### ISSUE THREAD

**Issue by jglick** [jelmerk/maven-settings-decoder#6]
I have both OpenJDK 8 & 11 installed, with 8 as the default. I ran a Gradle build and tried to run the result but it crashed with an error about bytecode version; only worked when I overrode `JAVA_HOME` to point to 11. I presume this has to do with `build.gradle` not mentioning a Java level and defaulting to whatever is chosen by the copy of `javac` that happened to be used. Since the sources seem to be 8-compatible I would suggest enforcing that so that the binary will work on any supported version of Java.

**Comment by jelmerk** [comment]
fixed
